#include "SymInstr.h"

#define OUTPUT_CLASS_NAME OutputX86
#define OUTPUT32

#define DEFAULT_STACK_POINTER SYMREG_NATIVE_REG(REG_ESP)
#define DEFAULT_FRAME_POINTER SYMREG_NATIVE_REG(REG_EBP)
#define DEFAULT_BASE_POINTER  SYMREG_NATIVE_REG(REG_EBX)

#include "OutputX86Common.cpp"
