#define OUTPUT_CLASS_NAME OutputX64
#define OUTPUT64

#define DEFAULT_STACK_POINTER SYMREG_NATIVE_REG(REG_ESP)
#define DEFAULT_FRAME_POINTER SYMREG_NATIVE_REG(REG_EBP)
#define DEFAULT_BASE_POINTER  SYMREG_NONE

#include "OutputX86Common.cpp"
