// Copyright (c) 2011-2012 Rusty Wagner
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#ifndef __SYSCALL_H__
#define __SYSCALL_H__

#define SYSCALL_CLASS_MACH 0x1000000
#define SYSCALL_CLASS_UNIX 0x2000000
#define SYSCALL_CLASS_MDEP 0x3000000
#define SYSCALL_CLASS_DIAG 0x4000000

#define SYS_syscall                        (  0 | SYSCALL_CLASS_UNIX)
#define SYS_exit                           (  1 | SYSCALL_CLASS_UNIX)
#define SYS_fork                           (  2 | SYSCALL_CLASS_UNIX)
#define SYS_read                           (  3 | SYSCALL_CLASS_UNIX)
#define SYS_write                          (  4 | SYSCALL_CLASS_UNIX)
#define SYS_open                           (  5 | SYSCALL_CLASS_UNIX)
#define SYS_close                          (  6 | SYSCALL_CLASS_UNIX)
#define SYS_wait4                          (  7 | SYSCALL_CLASS_UNIX)
#define SYS_link                           (  9 | SYSCALL_CLASS_UNIX)
#define SYS_unlink                         ( 10 | SYSCALL_CLASS_UNIX)
#define SYS_chdir                          ( 12 | SYSCALL_CLASS_UNIX)
#define SYS_fchdir                         ( 13 | SYSCALL_CLASS_UNIX)
#define SYS_mknod                          ( 14 | SYSCALL_CLASS_UNIX)
#define SYS_chmod                          ( 15 | SYSCALL_CLASS_UNIX)
#define SYS_chown                          ( 16 | SYSCALL_CLASS_UNIX)
#define SYS_getfsstat                      ( 18 | SYSCALL_CLASS_UNIX)
#define SYS_getpid                         ( 20 | SYSCALL_CLASS_UNIX)
#define SYS_setuid                         ( 23 | SYSCALL_CLASS_UNIX)
#define SYS_getuid                         ( 24 | SYSCALL_CLASS_UNIX)
#define SYS_geteuid                        ( 25 | SYSCALL_CLASS_UNIX)
#define SYS_ptrace                         ( 26 | SYSCALL_CLASS_UNIX)
#define SYS_recvmsg                        ( 27 | SYSCALL_CLASS_UNIX)
#define SYS_sendmsg                        ( 28 | SYSCALL_CLASS_UNIX)
#define SYS_recvfrom                       ( 29 | SYSCALL_CLASS_UNIX)
#define SYS_accept                         ( 30 | SYSCALL_CLASS_UNIX)
#define SYS_getpeername                    ( 31 | SYSCALL_CLASS_UNIX)
#define SYS_getsockname                    ( 32 | SYSCALL_CLASS_UNIX)
#define SYS_access                         ( 33 | SYSCALL_CLASS_UNIX)
#define SYS_chflags                        ( 34 | SYSCALL_CLASS_UNIX)
#define SYS_fchflags                       ( 35 | SYSCALL_CLASS_UNIX)
#define SYS_sync                           ( 36 | SYSCALL_CLASS_UNIX)
#define SYS_kill                           ( 37 | SYSCALL_CLASS_UNIX)
#define SYS_getppid                        ( 39 | SYSCALL_CLASS_UNIX)
#define SYS_dup                            ( 41 | SYSCALL_CLASS_UNIX)
#define SYS_pipe                           ( 42 | SYSCALL_CLASS_UNIX)
#define SYS_getegid                        ( 43 | SYSCALL_CLASS_UNIX)
#define SYS_profil                         ( 44 | SYSCALL_CLASS_UNIX)
#define SYS_sigaction                      ( 46 | SYSCALL_CLASS_UNIX)
#define SYS_getgid                         ( 47 | SYSCALL_CLASS_UNIX)
#define SYS_sigprocmask                    ( 48 | SYSCALL_CLASS_UNIX)
#define SYS_getlogin                       ( 49 | SYSCALL_CLASS_UNIX)
#define SYS_setlogin                       ( 50 | SYSCALL_CLASS_UNIX)
#define SYS_acct                           ( 51 | SYSCALL_CLASS_UNIX)
#define SYS_sigpending                     ( 52 | SYSCALL_CLASS_UNIX)
#define SYS_sigaltstack                    ( 53 | SYSCALL_CLASS_UNIX)
#define SYS_ioctl                          ( 54 | SYSCALL_CLASS_UNIX)
#define SYS_reboot                         ( 55 | SYSCALL_CLASS_UNIX)
#define SYS_revoke                         ( 56 | SYSCALL_CLASS_UNIX)
#define SYS_symlink                        ( 57 | SYSCALL_CLASS_UNIX)
#define SYS_readlink                       ( 58 | SYSCALL_CLASS_UNIX)
#define SYS_execve                         ( 59 | SYSCALL_CLASS_UNIX)
#define SYS_umask                          ( 60 | SYSCALL_CLASS_UNIX)
#define SYS_chroot                         ( 61 | SYSCALL_CLASS_UNIX)
#define SYS_msync                          ( 65 | SYSCALL_CLASS_UNIX)
#define SYS_vfork                          ( 66 | SYSCALL_CLASS_UNIX)
#define SYS_munmap                         ( 73 | SYSCALL_CLASS_UNIX)
#define SYS_mprotect                       ( 74 | SYSCALL_CLASS_UNIX)
#define SYS_madvise                        ( 75 | SYSCALL_CLASS_UNIX)
#define SYS_mincore                        ( 78 | SYSCALL_CLASS_UNIX)
#define SYS_getgroups                      ( 79 | SYSCALL_CLASS_UNIX)
#define SYS_setgroups                      ( 80 | SYSCALL_CLASS_UNIX)
#define SYS_getpgrp                        ( 81 | SYSCALL_CLASS_UNIX)
#define SYS_setpgid                        ( 82 | SYSCALL_CLASS_UNIX)
#define SYS_setitimer                      ( 83 | SYSCALL_CLASS_UNIX)
#define SYS_swapon                         ( 85 | SYSCALL_CLASS_UNIX)
#define SYS_getitimer                      ( 86 | SYSCALL_CLASS_UNIX)
#define SYS_getdtablesize                  ( 89 | SYSCALL_CLASS_UNIX)
#define SYS_dup2                           ( 90 | SYSCALL_CLASS_UNIX)
#define SYS_fcntl                          ( 92 | SYSCALL_CLASS_UNIX)
#define SYS_select                         ( 93 | SYSCALL_CLASS_UNIX)
#define SYS_fsync                          ( 95 | SYSCALL_CLASS_UNIX)
#define SYS_setpriority                    ( 96 | SYSCALL_CLASS_UNIX)
#define SYS_socket                         ( 97 | SYSCALL_CLASS_UNIX)
#define SYS_connect                        ( 98 | SYSCALL_CLASS_UNIX)
#define SYS_getpriority                    (100 | SYSCALL_CLASS_UNIX)
#define SYS_bind                           (104 | SYSCALL_CLASS_UNIX)
#define SYS_setsockopt                     (105 | SYSCALL_CLASS_UNIX)
#define SYS_listen                         (106 | SYSCALL_CLASS_UNIX)
#define SYS_sigsuspend                     (111 | SYSCALL_CLASS_UNIX)
#define SYS_gettimeofday                   (116 | SYSCALL_CLASS_UNIX)
#define SYS_getrusage                      (117 | SYSCALL_CLASS_UNIX)
#define SYS_getsockopt                     (118 | SYSCALL_CLASS_UNIX)
#define SYS_readv                          (120 | SYSCALL_CLASS_UNIX)
#define SYS_writev                         (121 | SYSCALL_CLASS_UNIX)
#define SYS_settimeofday                   (122 | SYSCALL_CLASS_UNIX)
#define SYS_fchown                         (123 | SYSCALL_CLASS_UNIX)
#define SYS_fchmod                         (124 | SYSCALL_CLASS_UNIX)
#define SYS_setreuid                       (126 | SYSCALL_CLASS_UNIX)
#define SYS_setregid                       (127 | SYSCALL_CLASS_UNIX)
#define SYS_rename                         (128 | SYSCALL_CLASS_UNIX)
#define SYS_flock                          (131 | SYSCALL_CLASS_UNIX)
#define SYS_mkfifo                         (132 | SYSCALL_CLASS_UNIX)
#define SYS_sendto                         (133 | SYSCALL_CLASS_UNIX)
#define SYS_shutdown                       (134 | SYSCALL_CLASS_UNIX)
#define SYS_socketpair                     (135 | SYSCALL_CLASS_UNIX)
#define SYS_mkdir                          (136 | SYSCALL_CLASS_UNIX)
#define SYS_rmdir                          (137 | SYSCALL_CLASS_UNIX)
#define SYS_utimes                         (138 | SYSCALL_CLASS_UNIX)
#define SYS_futimes                        (139 | SYSCALL_CLASS_UNIX)
#define SYS_adjtime                        (140 | SYSCALL_CLASS_UNIX)
#define SYS_gethostuuid                    (142 | SYSCALL_CLASS_UNIX)
#define SYS_setsid                         (147 | SYSCALL_CLASS_UNIX)
#define SYS_getpgid                        (151 | SYSCALL_CLASS_UNIX)
#define SYS_setprivexec                    (152 | SYSCALL_CLASS_UNIX)
#define SYS_pread                          (153 | SYSCALL_CLASS_UNIX)
#define SYS_pwrite                         (154 | SYSCALL_CLASS_UNIX)
#define SYS_nfssvc                         (155 | SYSCALL_CLASS_UNIX)
#define SYS_statfs                         (157 | SYSCALL_CLASS_UNIX)
#define SYS_fstatfs                        (158 | SYSCALL_CLASS_UNIX)
#define SYS_unmount                        (159 | SYSCALL_CLASS_UNIX)
#define SYS_getfh                          (161 | SYSCALL_CLASS_UNIX)
#define SYS_quotactl                       (165 | SYSCALL_CLASS_UNIX)
#define SYS_mount                          (167 | SYSCALL_CLASS_UNIX)
#define SYS_csops                          (169 | SYSCALL_CLASS_UNIX)
#define SYS_waitid                         (173 | SYSCALL_CLASS_UNIX)
#define SYS_add_profil                     (176 | SYSCALL_CLASS_UNIX)
#define SYS_kdebug_trace                   (180 | SYSCALL_CLASS_UNIX)
#define SYS_setgid                         (181 | SYSCALL_CLASS_UNIX)
#define SYS_setegid                        (182 | SYSCALL_CLASS_UNIX)
#define SYS_seteuid                        (183 | SYSCALL_CLASS_UNIX)
#define SYS_sigreturn                      (184 | SYSCALL_CLASS_UNIX)
#define SYS_chud                           (185 | SYSCALL_CLASS_UNIX)
#define SYS_fdatasync                      (187 | SYSCALL_CLASS_UNIX)
#define SYS_stat                           (188 | SYSCALL_CLASS_UNIX)
#define SYS_fstat                          (189 | SYSCALL_CLASS_UNIX)
#define SYS_lstat                          (190 | SYSCALL_CLASS_UNIX)
#define SYS_pathconf                       (191 | SYSCALL_CLASS_UNIX)
#define SYS_fpathconf                      (192 | SYSCALL_CLASS_UNIX)
#define SYS_getrlimit                      (194 | SYSCALL_CLASS_UNIX)
#define SYS_setrlimit                      (195 | SYSCALL_CLASS_UNIX)
#define SYS_getdirentries                  (196 | SYSCALL_CLASS_UNIX)
#define SYS_mmap                           (197 | SYSCALL_CLASS_UNIX)
#define SYS_lseek                          (199 | SYSCALL_CLASS_UNIX)
#define SYS_truncate                       (200 | SYSCALL_CLASS_UNIX)
#define SYS_ftruncate                      (201 | SYSCALL_CLASS_UNIX)
#define SYS___sysctl                       (202 | SYSCALL_CLASS_UNIX)
#define SYS_mlock                          (203 | SYSCALL_CLASS_UNIX)
#define SYS_munlock                        (204 | SYSCALL_CLASS_UNIX)
#define SYS_undelete                       (205 | SYSCALL_CLASS_UNIX)
#define SYS_ATsocket                       (206 | SYSCALL_CLASS_UNIX)
#define SYS_ATgetmsg                       (207 | SYSCALL_CLASS_UNIX)
#define SYS_ATputmsg                       (208 | SYSCALL_CLASS_UNIX)
#define SYS_ATPsndreq                      (209 | SYSCALL_CLASS_UNIX)
#define SYS_ATPsndrsp                      (210 | SYSCALL_CLASS_UNIX)
#define SYS_ATPgetreq                      (211 | SYSCALL_CLASS_UNIX)
#define SYS_ATPgetrsp                      (212 | SYSCALL_CLASS_UNIX)
#define SYS_mkcomplex                      (216 | SYSCALL_CLASS_UNIX)
#define SYS_statv                          (217 | SYSCALL_CLASS_UNIX)
#define SYS_lstatv                         (218 | SYSCALL_CLASS_UNIX)
#define SYS_fstatv                         (219 | SYSCALL_CLASS_UNIX)
#define SYS_getattrlist                    (220 | SYSCALL_CLASS_UNIX)
#define SYS_setattrlist                    (221 | SYSCALL_CLASS_UNIX)
#define SYS_getdirentriesattr              (222 | SYSCALL_CLASS_UNIX)
#define SYS_exchangedata                   (223 | SYSCALL_CLASS_UNIX)
#define SYS_searchfs                       (225 | SYSCALL_CLASS_UNIX)
#define SYS_delete                         (226 | SYSCALL_CLASS_UNIX)
#define SYS_copyfile                       (227 | SYSCALL_CLASS_UNIX)
#define SYS_fgetattrlist                   (228 | SYSCALL_CLASS_UNIX)
#define SYS_fsetattrlist                   (229 | SYSCALL_CLASS_UNIX)
#define SYS_poll                           (230 | SYSCALL_CLASS_UNIX)
#define SYS_watchevent                     (231 | SYSCALL_CLASS_UNIX)
#define SYS_waitevent                      (232 | SYSCALL_CLASS_UNIX)
#define SYS_modwatch                       (233 | SYSCALL_CLASS_UNIX)
#define SYS_getxattr                       (234 | SYSCALL_CLASS_UNIX)
#define SYS_fgetxattr                      (235 | SYSCALL_CLASS_UNIX)
#define SYS_setxattr                       (236 | SYSCALL_CLASS_UNIX)
#define SYS_fsetxattr                      (237 | SYSCALL_CLASS_UNIX)
#define SYS_removexattr                    (238 | SYSCALL_CLASS_UNIX)
#define SYS_fremovexattr                   (239 | SYSCALL_CLASS_UNIX)
#define SYS_listxattr                      (240 | SYSCALL_CLASS_UNIX)
#define SYS_flistxattr                     (241 | SYSCALL_CLASS_UNIX)
#define SYS_fsctl                          (242 | SYSCALL_CLASS_UNIX)
#define SYS_initgroups                     (243 | SYSCALL_CLASS_UNIX)
#define SYS_posix_spawn                    (244 | SYSCALL_CLASS_UNIX)
#define SYS_ffsctl                         (245 | SYSCALL_CLASS_UNIX)
#define SYS_nfsclnt                        (247 | SYSCALL_CLASS_UNIX)
#define SYS_fhopen                         (248 | SYSCALL_CLASS_UNIX)
#define SYS_minherit                       (250 | SYSCALL_CLASS_UNIX)
#define SYS_semsys                         (251 | SYSCALL_CLASS_UNIX)
#define SYS_msgsys                         (252 | SYSCALL_CLASS_UNIX)
#define SYS_shmsys                         (253 | SYSCALL_CLASS_UNIX)
#define SYS_semctl                         (254 | SYSCALL_CLASS_UNIX)
#define SYS_semget                         (255 | SYSCALL_CLASS_UNIX)
#define SYS_semop                          (256 | SYSCALL_CLASS_UNIX)
#define SYS_msgctl                         (258 | SYSCALL_CLASS_UNIX)
#define SYS_msgget                         (259 | SYSCALL_CLASS_UNIX)
#define SYS_msgsnd                         (260 | SYSCALL_CLASS_UNIX)
#define SYS_msgrcv                         (261 | SYSCALL_CLASS_UNIX)
#define SYS_shmat                          (262 | SYSCALL_CLASS_UNIX)
#define SYS_shmctl                         (263 | SYSCALL_CLASS_UNIX)
#define SYS_shmdt                          (264 | SYSCALL_CLASS_UNIX)
#define SYS_shmget                         (265 | SYSCALL_CLASS_UNIX)
#define SYS_shm_open                       (266 | SYSCALL_CLASS_UNIX)
#define SYS_shm_unlink                     (267 | SYSCALL_CLASS_UNIX)
#define SYS_sem_open                       (268 | SYSCALL_CLASS_UNIX)
#define SYS_sem_close                      (269 | SYSCALL_CLASS_UNIX)
#define SYS_sem_unlink                     (270 | SYSCALL_CLASS_UNIX)
#define SYS_sem_wait                       (271 | SYSCALL_CLASS_UNIX)
#define SYS_sem_trywait                    (272 | SYSCALL_CLASS_UNIX)
#define SYS_sem_post                       (273 | SYSCALL_CLASS_UNIX)
#define SYS_sem_getvalue                   (274 | SYSCALL_CLASS_UNIX)
#define SYS_sem_init                       (275 | SYSCALL_CLASS_UNIX)
#define SYS_sem_destroy                    (276 | SYSCALL_CLASS_UNIX)
#define SYS_open_extended                  (277 | SYSCALL_CLASS_UNIX)
#define SYS_umask_extended                 (278 | SYSCALL_CLASS_UNIX)
#define SYS_stat_extended                  (279 | SYSCALL_CLASS_UNIX)
#define SYS_lstat_extended                 (280 | SYSCALL_CLASS_UNIX)
#define SYS_fstat_extended                 (281 | SYSCALL_CLASS_UNIX)
#define SYS_chmod_extended                 (282 | SYSCALL_CLASS_UNIX)
#define SYS_fchmod_extended                (283 | SYSCALL_CLASS_UNIX)
#define SYS_access_extended                (284 | SYSCALL_CLASS_UNIX)
#define SYS_settid                         (285 | SYSCALL_CLASS_UNIX)
#define SYS_gettid                         (286 | SYSCALL_CLASS_UNIX)
#define SYS_setsgroups                     (287 | SYSCALL_CLASS_UNIX)
#define SYS_getsgroups                     (288 | SYSCALL_CLASS_UNIX)
#define SYS_setwgroups                     (289 | SYSCALL_CLASS_UNIX)
#define SYS_getwgroups                     (290 | SYSCALL_CLASS_UNIX)
#define SYS_mkfifo_extended                (291 | SYSCALL_CLASS_UNIX)
#define SYS_mkdir_extended                 (292 | SYSCALL_CLASS_UNIX)
#define SYS_identitysvc                    (293 | SYSCALL_CLASS_UNIX)
#define SYS_shared_region_check_np         (294 | SYSCALL_CLASS_UNIX)
#define SYS_vm_pressure_monitor            (296 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_longrdlock           (297 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_yieldwrlock          (298 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_downgrade            (299 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_upgrade              (300 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_mutexwait               (301 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_mutexdrop               (302 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_cvbroad                 (303 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_cvsignal                (304 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_cvwait                  (305 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_rdlock               (306 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_wrlock               (307 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_unlock               (308 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_rw_unlock2              (309 | SYSCALL_CLASS_UNIX)
#define SYS_getsid                         (310 | SYSCALL_CLASS_UNIX)
#define SYS_settid_with_pid                (311 | SYSCALL_CLASS_UNIX)
#define SYS_psynch_cvclrprepost            (312 | SYSCALL_CLASS_UNIX)
#define SYS_aio_fsync                      (313 | SYSCALL_CLASS_UNIX)
#define SYS_aio_return                     (314 | SYSCALL_CLASS_UNIX)
#define SYS_aio_suspend                    (315 | SYSCALL_CLASS_UNIX)
#define SYS_aio_cancel                     (316 | SYSCALL_CLASS_UNIX)
#define SYS_aio_error                      (317 | SYSCALL_CLASS_UNIX)
#define SYS_aio_read                       (318 | SYSCALL_CLASS_UNIX)
#define SYS_aio_write                      (319 | SYSCALL_CLASS_UNIX)
#define SYS_lio_listio                     (320 | SYSCALL_CLASS_UNIX)
#define SYS_iopolicysys                    (322 | SYSCALL_CLASS_UNIX)
#define SYS_process_policy                 (323 | SYSCALL_CLASS_UNIX)
#define SYS_mlockall                       (324 | SYSCALL_CLASS_UNIX)
#define SYS_munlockall                     (325 | SYSCALL_CLASS_UNIX)
#define SYS_issetugid                      (327 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_kill                 (328 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_sigmask              (329 | SYSCALL_CLASS_UNIX)
#define SYS___sigwait                      (330 | SYSCALL_CLASS_UNIX)
#define SYS___disable_threadsignal         (331 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_markcancel           (332 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_canceled             (333 | SYSCALL_CLASS_UNIX)
#define SYS___semwait_signal               (334 | SYSCALL_CLASS_UNIX)
#define SYS_proc_info                      (336 | SYSCALL_CLASS_UNIX)
#define SYS_sendfile                       (337 | SYSCALL_CLASS_UNIX)
#define SYS_stat64                         (338 | SYSCALL_CLASS_UNIX)
#define SYS_fstat64                        (339 | SYSCALL_CLASS_UNIX)
#define SYS_lstat64                        (340 | SYSCALL_CLASS_UNIX)
#define SYS_stat64_extended                (341 | SYSCALL_CLASS_UNIX)
#define SYS_lstat64_extended               (342 | SYSCALL_CLASS_UNIX)
#define SYS_fstat64_extended               (343 | SYSCALL_CLASS_UNIX)
#define SYS_getdirentries64                (344 | SYSCALL_CLASS_UNIX)
#define SYS_statfs64                       (345 | SYSCALL_CLASS_UNIX)
#define SYS_fstatfs64                      (346 | SYSCALL_CLASS_UNIX)
#define SYS_getfsstat64                    (347 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_chdir                (348 | SYSCALL_CLASS_UNIX)
#define SYS___pthread_fchdir               (349 | SYSCALL_CLASS_UNIX)
#define SYS_audit                          (350 | SYSCALL_CLASS_UNIX)
#define SYS_auditon                        (351 | SYSCALL_CLASS_UNIX)
#define SYS_getauid                        (353 | SYSCALL_CLASS_UNIX)
#define SYS_setauid                        (354 | SYSCALL_CLASS_UNIX)
#define SYS_getaudit                       (355 | SYSCALL_CLASS_UNIX)
#define SYS_setaudit                       (356 | SYSCALL_CLASS_UNIX)
#define SYS_getaudit_addr                  (357 | SYSCALL_CLASS_UNIX)
#define SYS_setaudit_addr                  (358 | SYSCALL_CLASS_UNIX)
#define SYS_auditctl                       (359 | SYSCALL_CLASS_UNIX)
#define SYS_bsdthread_create               (360 | SYSCALL_CLASS_UNIX)
#define SYS_bsdthread_terminate            (361 | SYSCALL_CLASS_UNIX)
#define SYS_kqueue                         (362 | SYSCALL_CLASS_UNIX)
#define SYS_kevent                         (363 | SYSCALL_CLASS_UNIX)
#define SYS_lchown                         (364 | SYSCALL_CLASS_UNIX)
#define SYS_stack_snapshot                 (365 | SYSCALL_CLASS_UNIX)
#define SYS_bsdthread_register             (366 | SYSCALL_CLASS_UNIX)
#define SYS_workq_open                     (367 | SYSCALL_CLASS_UNIX)
#define SYS_workq_kernreturn               (368 | SYSCALL_CLASS_UNIX)
#define SYS_kevent64                       (369 | SYSCALL_CLASS_UNIX)
#define SYS___old_semwait_signal           (370 | SYSCALL_CLASS_UNIX)
#define SYS___old_semwait_signal_nocancel  (371 | SYSCALL_CLASS_UNIX)
#define SYS_thread_selfid                  (372 | SYSCALL_CLASS_UNIX)
#define SYS___mac_execve                   (380 | SYSCALL_CLASS_UNIX)
#define SYS___mac_syscall                  (381 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_file                 (382 | SYSCALL_CLASS_UNIX)
#define SYS___mac_set_file                 (383 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_link                 (384 | SYSCALL_CLASS_UNIX)
#define SYS___mac_set_link                 (385 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_proc                 (386 | SYSCALL_CLASS_UNIX)
#define SYS___mac_set_proc                 (387 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_fd                   (388 | SYSCALL_CLASS_UNIX)
#define SYS___mac_set_fd                   (389 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_pid                  (390 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_lcid                 (391 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_lctx                 (392 | SYSCALL_CLASS_UNIX)
#define SYS___mac_set_lctx                 (393 | SYSCALL_CLASS_UNIX)
#define SYS_setlcid                        (394 | SYSCALL_CLASS_UNIX)
#define SYS_getlcid                        (395 | SYSCALL_CLASS_UNIX)
#define SYS_read_nocancel                  (396 | SYSCALL_CLASS_UNIX)
#define SYS_write_nocancel                 (397 | SYSCALL_CLASS_UNIX)
#define SYS_open_nocancel                  (398 | SYSCALL_CLASS_UNIX)
#define SYS_close_nocancel                 (399 | SYSCALL_CLASS_UNIX)
#define SYS_wait4_nocancel                 (400 | SYSCALL_CLASS_UNIX)
#define SYS_recvmsg_nocancel               (401 | SYSCALL_CLASS_UNIX)
#define SYS_sendmsg_nocancel               (402 | SYSCALL_CLASS_UNIX)
#define SYS_recvfrom_nocancel              (403 | SYSCALL_CLASS_UNIX)
#define SYS_accept_nocancel                (404 | SYSCALL_CLASS_UNIX)
#define SYS_msync_nocancel                 (405 | SYSCALL_CLASS_UNIX)
#define SYS_fcntl_nocancel                 (406 | SYSCALL_CLASS_UNIX)
#define SYS_select_nocancel                (407 | SYSCALL_CLASS_UNIX)
#define SYS_fsync_nocancel                 (408 | SYSCALL_CLASS_UNIX)
#define SYS_connect_nocancel               (409 | SYSCALL_CLASS_UNIX)
#define SYS_sigsuspend_nocancel            (410 | SYSCALL_CLASS_UNIX)
#define SYS_readv_nocancel                 (411 | SYSCALL_CLASS_UNIX)
#define SYS_writev_nocancel                (412 | SYSCALL_CLASS_UNIX)
#define SYS_sendto_nocancel                (413 | SYSCALL_CLASS_UNIX)
#define SYS_pread_nocancel                 (414 | SYSCALL_CLASS_UNIX)
#define SYS_pwrite_nocancel                (415 | SYSCALL_CLASS_UNIX)
#define SYS_waitid_nocancel                (416 | SYSCALL_CLASS_UNIX)
#define SYS_poll_nocancel                  (417 | SYSCALL_CLASS_UNIX)
#define SYS_msgsnd_nocancel                (418 | SYSCALL_CLASS_UNIX)
#define SYS_msgrcv_nocancel                (419 | SYSCALL_CLASS_UNIX)
#define SYS_sem_wait_nocancel              (420 | SYSCALL_CLASS_UNIX)
#define SYS_aio_suspend_nocancel           (421 | SYSCALL_CLASS_UNIX)
#define SYS___sigwait_nocancel             (422 | SYSCALL_CLASS_UNIX)
#define SYS___semwait_signal_nocancel      (423 | SYSCALL_CLASS_UNIX)
#define SYS___mac_mount                    (424 | SYSCALL_CLASS_UNIX)
#define SYS___mac_get_mount                (425 | SYSCALL_CLASS_UNIX)
#define SYS___mac_getfsstat                (426 | SYSCALL_CLASS_UNIX)
#define SYS_fsgetpath                      (427 | SYSCALL_CLASS_UNIX)
#define SYS_audit_session_self             (428 | SYSCALL_CLASS_UNIX)
#define SYS_audit_session_join             (429 | SYSCALL_CLASS_UNIX)
#define SYS_fileport_makeport              (430 | SYSCALL_CLASS_UNIX)
#define SYS_fileport_makefd                (431 | SYSCALL_CLASS_UNIX)
#define SYS_audit_session_port             (432 | SYSCALL_CLASS_UNIX)
#define SYS_pid_suspend                    (433 | SYSCALL_CLASS_UNIX)
#define SYS_pid_resume                     (434 | SYSCALL_CLASS_UNIX)
#define SYS_pid_hibernate                  (435 | SYSCALL_CLASS_UNIX)
#define SYS_pid_shutdown_sockets           (436 | SYSCALL_CLASS_UNIX)
#define SYS_shared_region_map_and_slide_np (438 | SYSCALL_CLASS_UNIX)

#endif

